set_property PACKAGE_PIN C2  [get_ports {io_ddr_pad_mem_data_0[0] }]
set_property PACKAGE_PIN G1  [get_ports {io_ddr_pad_mem_data_0[1] }]
set_property PACKAGE_PIN A1  [get_ports {io_ddr_pad_mem_data_0[2] }]
set_property PACKAGE_PIN F3  [get_ports {io_ddr_pad_mem_data_0[3] }]
set_property PACKAGE_PIN B2  [get_ports {io_ddr_pad_mem_data_0[4] }]
set_property PACKAGE_PIN F1  [get_ports {io_ddr_pad_mem_data_0[5] }]
set_property PACKAGE_PIN B1  [get_ports {io_ddr_pad_mem_data_0[6] }]
set_property PACKAGE_PIN E2  [get_ports {io_ddr_pad_mem_data_0[7] }]
set_property PACKAGE_PIN H3  [get_ports {io_ddr_pad_mem_data_0[8] }]
set_property PACKAGE_PIN G3  [get_ports {io_ddr_pad_mem_data_0[9] }]
set_property PACKAGE_PIN H2  [get_ports {io_ddr_pad_mem_data_0[10]}]
set_property PACKAGE_PIN H5  [get_ports {io_ddr_pad_mem_data_0[11]}]
set_property PACKAGE_PIN J1  [get_ports {io_ddr_pad_mem_data_0[12]}]
set_property PACKAGE_PIN J5  [get_ports {io_ddr_pad_mem_data_0[13]}]
set_property PACKAGE_PIN K1  [get_ports {io_ddr_pad_mem_data_0[14]}]
set_property PACKAGE_PIN H4  [get_ports {io_ddr_pad_mem_data_0[15]}]
set_property PACKAGE_PIN L4  [get_ports {io_ddr_pad_mem_data_1[0] }]
set_property PACKAGE_PIN M3  [get_ports {io_ddr_pad_mem_data_1[1] }]
set_property PACKAGE_PIN L3  [get_ports {io_ddr_pad_mem_data_1[2] }]
set_property PACKAGE_PIN J6  [get_ports {io_ddr_pad_mem_data_1[3] }]
set_property PACKAGE_PIN K3  [get_ports {io_ddr_pad_mem_data_1[4] }]
set_property PACKAGE_PIN K6  [get_ports {io_ddr_pad_mem_data_1[5] }]
set_property PACKAGE_PIN J4  [get_ports {io_ddr_pad_mem_data_1[6] }]
set_property PACKAGE_PIN L5  [get_ports {io_ddr_pad_mem_data_1[7] }]
set_property PACKAGE_PIN P1  [get_ports {io_ddr_pad_mem_data_1[8] }]
set_property PACKAGE_PIN N4  [get_ports {io_ddr_pad_mem_data_1[9] }]
set_property PACKAGE_PIN R1  [get_ports {io_ddr_pad_mem_data_1[10]}]
set_property PACKAGE_PIN N2  [get_ports {io_ddr_pad_mem_data_1[11]}]
set_property PACKAGE_PIN M6  [get_ports {io_ddr_pad_mem_data_1[12]}]
set_property PACKAGE_PIN N5  [get_ports {io_ddr_pad_mem_data_1[13]}]
set_property PACKAGE_PIN P6  [get_ports {io_ddr_pad_mem_data_1[14]}]
set_property PACKAGE_PIN P2  [get_ports {io_ddr_pad_mem_data_1[15]}]
set_property PACKAGE_PIN D2  [get_ports {io_ddr_pad_mem_dm_0[0]   }]
set_property PACKAGE_PIN G2  [get_ports {io_ddr_pad_mem_dm_0[1]   }]
set_property PACKAGE_PIN M2  [get_ports {io_ddr_pad_mem_dm_1[0]   }]
set_property PACKAGE_PIN M5  [get_ports {io_ddr_pad_mem_dm_1[1]   }]
set_property PACKAGE_PIN E1  [get_ports {io_ddr_pad_mem_dqs_0[0]  }]
set_property PACKAGE_PIN D1  [get_ports {io_ddr_pad_mem_dqs_n_0[0]}]
set_property PACKAGE_PIN K2  [get_ports {io_ddr_pad_mem_dqs_0[1]  }]
set_property PACKAGE_PIN J2  [get_ports {io_ddr_pad_mem_dqs_n_0[1]}]
set_property PACKAGE_PIN M1  [get_ports {io_ddr_pad_mem_dqs_1[0]  }]
set_property PACKAGE_PIN L1  [get_ports {io_ddr_pad_mem_dqs_n_1[0]}]
set_property PACKAGE_PIN P5  [get_ports {io_ddr_pad_mem_dqs_1[1]  }]
set_property PACKAGE_PIN P4  [get_ports {io_ddr_pad_mem_dqs_n_1[1]}]
set_property PACKAGE_PIN V3  [get_ports {io_ddr_mem_address[14]   }]
set_property PACKAGE_PIN U1  [get_ports {io_ddr_mem_address[13]   }]
set_property PACKAGE_PIN Y2  [get_ports {io_ddr_mem_address[12]   }]
set_property PACKAGE_PIN W2  [get_ports {io_ddr_mem_address[11]   }]
set_property PACKAGE_PIN Y1  [get_ports {io_ddr_mem_address[10]   }]
set_property PACKAGE_PIN U2  [get_ports {io_ddr_mem_address[9]    }]
set_property PACKAGE_PIN V2  [get_ports {io_ddr_mem_address[8]    }]
set_property PACKAGE_PIN T1  [get_ports {io_ddr_mem_address[7]    }]
set_property PACKAGE_PIN W1  [get_ports {io_ddr_mem_address[6]    }]
set_property PACKAGE_PIN U3  [get_ports {io_ddr_mem_address[5]    }]
set_property PACKAGE_PIN AB1 [get_ports {io_ddr_mem_address[4]    }]
set_property PACKAGE_PIN AB5 [get_ports {io_ddr_mem_address[3]    }]
set_property PACKAGE_PIN AA5 [get_ports {io_ddr_mem_address[2]    }]
set_property PACKAGE_PIN AB2 [get_ports {io_ddr_mem_address[1]    }]
set_property PACKAGE_PIN AA4 [get_ports {io_ddr_mem_address[0]    }]
set_property PACKAGE_PIN Y4  [get_ports {io_ddr_mem_bank[2]       }]
set_property PACKAGE_PIN Y3  [get_ports {io_ddr_mem_bank[1]       }]
set_property PACKAGE_PIN AA3 [get_ports {io_ddr_mem_bank[0]       }]
set_property PACKAGE_PIN R3  [get_ports io_ddr_mem_clk             ]
set_property PACKAGE_PIN R2  [get_ports io_ddr_mem_clk_n           ]
set_property PACKAGE_PIN V4  [get_ports io_ddr_mem_ras_n           ]
set_property PACKAGE_PIN W4  [get_ports io_ddr_mem_cas_n           ]
set_property PACKAGE_PIN AA1 [get_ports io_ddr_mem_we_n            ]
set_property PACKAGE_PIN W6  [get_ports io_ddr_mem_reset_n         ]
set_property PACKAGE_PIN T5  [get_ports io_ddr_mem_cke             ]
set_property PACKAGE_PIN U5  [get_ports io_ddr_mem_odt             ]
set_property PACKAGE_PIN AB3 [get_ports io_ddr_mem_cs_n            ]

set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[0]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[0]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[0]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[1]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[1]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[1]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[2]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[2]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[2]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[3]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[3]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[3]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[4]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[4]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[4]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[5]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[5]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[5]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[6]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[6]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[6]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[7]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[7]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[7]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[8]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[8]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[8]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[9]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[9]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[9]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[10] }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[10] }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[10] }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[11] }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[11] }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[11] }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[12] }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[12] }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[12] }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[13] }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[13] }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[13] }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[14] }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[14] }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[14] }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_0[15] }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_0[15] }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_0[15] }]


set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[0]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[0]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[0]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[1]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[1]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[1]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[2]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[2]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[2]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[3]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[3]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[3]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[4]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[4]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[4]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[5]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[5]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[5]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[6]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[6]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[6]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[7]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[7]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[7]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[8]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[8]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[8]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[9]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[9]  }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[9]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[10] }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[10] }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[10] }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[11] }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[11] }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[11] }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[12] }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[12] }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[12] }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[13] }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[13] }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[13] }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[14] }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[14] }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[14] }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_data_1[15] }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_data_1[15] }]
set_property IOSTANDARD  SSTL15       [get_ports {io_ddr_pad_mem_data_1[15] }]

set_property SLEW FAST               [get_ports {io_ddr_pad_mem_dm_0[0]   }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_pad_mem_dm_0[0]   }]
set_property SLEW FAST               [get_ports {io_ddr_pad_mem_dm_0[1]   }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_pad_mem_dm_0[1]   }]
set_property SLEW FAST               [get_ports {io_ddr_pad_mem_dm_1[0]   }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_pad_mem_dm_1[0]   }]
set_property SLEW FAST               [get_ports {io_ddr_pad_mem_dm_1[1]   }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_pad_mem_dm_1[1]   }]

set_property SLEW FAST                [get_ports {io_ddr_pad_mem_dqs_0[0]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_dqs_0[0]  }]
set_property IOSTANDARD  DIFF_SSTL15  [get_ports {io_ddr_pad_mem_dqs_0[0]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_dqs_n_0[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_dqs_n_0[0]}]
set_property IOSTANDARD  DIFF_SSTL15  [get_ports {io_ddr_pad_mem_dqs_n_0[0]}]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_dqs_0[1]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_dqs_0[1]  }]
set_property IOSTANDARD  DIFF_SSTL15  [get_ports {io_ddr_pad_mem_dqs_0[1]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_dqs_n_0[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_dqs_n_0[1]}]
set_property IOSTANDARD  DIFF_SSTL15  [get_ports {io_ddr_pad_mem_dqs_n_0[1]}]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_dqs_1[0]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_dqs_1[0]  }]
set_property IOSTANDARD  DIFF_SSTL15  [get_ports {io_ddr_pad_mem_dqs_1[0]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_dqs_n_1[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_dqs_n_1[0]}]
set_property IOSTANDARD  DIFF_SSTL15  [get_ports {io_ddr_pad_mem_dqs_n_1[0]}]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_dqs_1[1]  }]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_dqs_1[1]  }]
set_property IOSTANDARD  DIFF_SSTL15  [get_ports {io_ddr_pad_mem_dqs_1[1]  }]
set_property SLEW FAST                [get_ports {io_ddr_pad_mem_dqs_n_1[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {io_ddr_pad_mem_dqs_n_1[1]}]
set_property IOSTANDARD  DIFF_SSTL15  [get_ports {io_ddr_pad_mem_dqs_n_1[1]}]


set_property SLEW FAST               [get_ports {io_ddr_mem_address[14]   }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[14]   }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[13]   }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[13]   }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[12]   }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[12]   }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[11]   }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[11]   }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[10]   }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[10]   }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[9]    }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[9]    }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[8]    }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[8]    }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[7]    }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[7]    }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[6]    }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[6]    }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[5]    }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[5]    }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[4]    }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[4]    }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[3]    }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[3]    }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[2]    }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[2]    }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[1]    }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[1]    }]
set_property SLEW FAST               [get_ports {io_ddr_mem_address[0]    }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_address[0]    }]

set_property SLEW FAST               [get_ports {io_ddr_mem_bank[2]       }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_bank[2]       }]
set_property SLEW FAST               [get_ports {io_ddr_mem_bank[1]       }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_bank[1]       }]
set_property SLEW FAST               [get_ports {io_ddr_mem_bank[0]       }]
set_property IOSTANDARD  SSTL15      [get_ports {io_ddr_mem_bank[0]       }]

set_property IO_BUFFER_TYPE NONE [get_ports io_ddr_mem_clk]
set_property IO_BUFFER_TYPE NONE [get_ports io_ddr_mem_clk_n]

set_property SLEW FAST               [get_ports io_ddr_mem_clk             ]
set_property IOSTANDARD  DIFF_SSTL15 [get_ports io_ddr_mem_clk             ]
set_property SLEW FAST               [get_ports io_ddr_mem_clk_n           ]
set_property IOSTANDARD  DIFF_SSTL15 [get_ports io_ddr_mem_clk_n           ]
set_property SLEW FAST               [get_ports io_ddr_mem_ras_n           ]
set_property IOSTANDARD  SSTL15      [get_ports io_ddr_mem_ras_n           ]
set_property SLEW FAST               [get_ports io_ddr_mem_cas_n           ]
set_property IOSTANDARD  SSTL15      [get_ports io_ddr_mem_cas_n           ]
set_property SLEW FAST               [get_ports io_ddr_mem_we_n            ]
set_property IOSTANDARD  SSTL15      [get_ports io_ddr_mem_we_n            ]
set_property SLEW FAST               [get_ports io_ddr_mem_reset_n         ]
set_property IOSTANDARD  LVCMOS15    [get_ports io_ddr_mem_reset_n         ]
set_property SLEW FAST               [get_ports io_ddr_mem_cke             ]
set_property IOSTANDARD  SSTL15      [get_ports io_ddr_mem_cke             ]
set_property SLEW FAST               [get_ports io_ddr_mem_odt             ]
set_property IOSTANDARD  SSTL15      [get_ports io_ddr_mem_odt             ]
set_property SLEW FAST               [get_ports io_ddr_mem_cs_n            ]
set_property IOSTANDARD  SSTL15      [get_ports io_ddr_mem_cs_n            ]