  #define JTAG_ST_TestLogicReset  0
  #define JTAG_ST_RunTestIdle     1
  #define JTAG_ST_SelectDRScan    2
  #define JTAG_ST_CaptureDR       3
  #define JTAG_ST_ShiftDR         4
  #define JTAG_ST_Exit1DR         5
  #define JTAG_ST_PauseDR         6
  #define JTAG_ST_Exit2DR         7
  #define JTAG_ST_UpdateDR        8
  #define JTAG_ST_SelectIRScan    9
  #define JTAG_ST_CaptureIR      10
  #define JTAG_ST_ShiftIR        11
  #define JTAG_ST_Exit1IR        12
  #define JTAG_ST_PauseIR        13
  #define JTAG_ST_Exit2IR        14
  #define JTAG_ST_UpdateIR       15

  #define DMI2JTAG_ST_INIT       0
  #define DMI2JTAG_ST_REQ_CHECK  1
  #define DMI2JTAG_ST_REQ_READY  2
  #define DMI2JTAG_ST_REQ_SEND   3
  #define DMI2JTAG_ST_RESP_CHECK 4
  #define DMI2JTAG_ST_RESP_READY 5
  #define DMI2JTAG_ST_RESP_SEND  6
  #define DMI2JTAG_ST_RESP_DONE  7
  #define DMI2JTAG_ST_EXIT       8
