#!/bin/csh -f
#-MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON-
#-MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON-
#-MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON-
#
#  N25Q064A13E
#
#  Verilog Behavioral Model
#  Version 1.0
#
#  Copyright (c) 2013 Micron Inc.
#
#-MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON-
#-MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON-
#-MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON--MICRON-


set RUNDIR  = ./
set CODEDIR = ./code
set STIMDIR = ./stim
set TOPDIR  = ./top
set SIMDIR  = ./sim


if (-e $SIMDIR/work) then
\rm -r $SIMDIR/work
endif
vlib $SIMDIR/work


#CODE
vlog -work $SIMDIR/work $CODEDIR/N25Qxxx.v
if ( $status != 0 ) exit 2


#STIM
vlog -work $SIMDIR/work $STIMDIR/read.v
#vlog -work $SIMDIR/work $STIMDIR/program.v
if ( $status != 0 ) exit 3


#TOP
vlog -work $SIMDIR/work $TOPDIR/Testbench.v
if ( $status != 0 ) exit 4
vlog -work $SIMDIR/work $TOPDIR/StimTasks.v
if ( $status != 0 ) exit 4
vlog -work $SIMDIR/work $TOPDIR/ClockGenerator.v
if ( $status != 0 ) exit 4


# Simulate
cd $SIMDIR
#vsim -gui -t 1fs work.Testbench  -novopt $1 &
#vsim -gui -t 1fs work.Testbench -do do.do  -novopt $1 &
vsim -t 1fs work.Testbench -do do.do  -novopt $1 &
if ( $status != 0 ) exit 5


